[package]
name = "dist_corr"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "=0.14.0"
criterion = "=0.5.1"
rand_chacha = "0.3.1"
rand = "=0.8.5"
rayon = "=1.10.0"


#--------------------------------------------------
# Features

[[bench]]
name = "dist_corr_speed_test"
harness = false
